p1/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('service/', include('service.urls')),
    path('send_mail/', include('send_mail.urls')),
    path('send_sms/', include('send_sms.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

                 ]

service/urls.py
from django.urls import path
from . import views

app_name = 'service'
urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'add/', views.add, name='add'),
    path(r'consuming/', views.consuming, name='consuming'),
    path(r'upd/', views.consuming_upd, name='upd'),

]

service/models.py
#coding: utf-8
from django.db import models
from django.utils import timezone

class Services(models.Model):
    class Meta():
        db_table = 'services'

    hot_water = models.DecimalField('Hot water', max_digits=10, decimal_places=1)
    cold_water = models.DecimalField('Cold water', max_digits=10, decimal_places=1)
    electricity = models.DecimalField('Electricity', max_digits=10, decimal_places=1)
    gaz = models.DecimalField('Gaz', max_digits=10, decimal_places=1)
    pub_date = models.DateField('Publication date')


class Consumption(models.Model):
    class Meta():
        db_table = 'consumption'

    hot_water = models.DecimalField('Hot water', max_digits=10, decimal_places=1)
    cold_water = models.DecimalField('Cold water', max_digits=10, decimal_places=1)
    electricity = models.DecimalField('Electricity', max_digits=10, decimal_places=1)
    gaz = models.DecimalField('Gaz', max_digits=10, decimal_places=1)
    pub_date = models.DateField('Publication date')

service/forms.py
from django import forms
from .models import Services


class AddForm(forms.ModelForm):	
    def __init__(self, *args, **kwargs):
        super(AddForm, self).__init__(*args, **kwargs)
        self.fields['cold_water'].initial = '0'
        self.fields['hot_water'].initial = '0'


    class Meta:
        model = Services
        fields = ('cold_water','hot_water', 'electricity', 'gaz',)

        labels = {'cold_water': ('Холодная вода'),
        		  'hot_water': ('Горячая вода'),
                  'electricity': ('Электричество'),
                  'gaz': ('Газ'),
                  }
        

service/views.py
from django.shortcuts import render, redirect
from service.models import Services, Consumption
from .forms import AddForm
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required



def home(request):
    
    service = Services.objects.order_by('-id')
    paginator = Paginator(service, 6)
    page = request.GET.get('page')
    service = paginator.get_page(page)
    context = {
        'service': service,
        'title': 'Показания счетчиков',
               }
    
    return render(request, 'service/index.html', context)

@login_required
def consuming(request):
    
    consumption = Consumption.objects.order_by('-id')
    paginator = Paginator(consumption, 6)
    page = request.GET.get('page')
    consumption = paginator.get_page(page)
    context = {
        'consumption': consumption,
        'title': 'Расход',
               }
    return render(request, 'service/consumption.html', context)

@login_required
def consuming_upd(request):
    
    Consumption.objects.all().delete()
    service = Services.objects.all()
    
    for item in range (len(service)-1):
        hot_water = service[item+1].hot_water - service[item].hot_water
        cold_water = service[item+1].cold_water - service[item].cold_water
        electricity = service[item+1].electricity - service[item].electricity
        gaz = service[item+1].gaz - service[item].gaz
        pub_date = service[item+1].pub_date
        consumption = Consumption.objects.create(hot_water=hot_water,
                                                cold_water=cold_water,
                                                electricity=electricity,
                                                gaz=gaz,
                                                pub_date=pub_date
                                                    )
        consumption.save()
    consumption = Consumption.objects.order_by('-id')
    paginator = Paginator(consumption, 6)
    page = request.GET.get('page')
    consumption = paginator.get_page(page)
    context = {
        'consumption': consumption,
        'title': 'Расход',
               }
    return render(request, 'service/consumption.html', context)


@login_required
def add(request):
    

    if request.method == "POST":
        form = AddForm(request.POST, request.FILES)
        if form.is_valid():
            service = form.save(commit=False)
            service.pub_date = timezone.now()
            service.save()
            service = Services.objects.order_by('-id')[:2]
            hot_water = service[0].hot_water - service[1].hot_water
            cold_water = service[0].cold_water - service[1].cold_water
            electricity = service[0].electricity - service[1].electricity
            gaz = service[0].gaz - service[1].gaz
            consumption = Consumption.objects.create(hot_water=hot_water,
                                                     cold_water=cold_water,
                                                     electricity=electricity,
                                                     gaz=gaz,
                                                     pub_date=timezone.now()
                                                    )
            consumption.save()
            return redirect('service:home')
    else:
        form = AddForm()
    context = {
        'form': form,
        'title': 'Добавить показания счетчиков',
               }
    return render(request, 'service/add.html', context)

service/templates/service/add.html
{% extends 'base.html' %}
{% block content%}
 
<div class="row">
	<form class="col s12" enctype="multipart/form-data" method="POST" id="form_ID">
		{% csrf_token %} 
		<div class="row">
			<div class="input-field col s12 m3">
				<input name="val1" type="text" value=""></input>
				<label>Хол.вода кухня</label>
			</div>	
			<div class="input-field col s12 m3">	
				<input name="val2" type="text" value="" oninput="{{ form.cold_water.id_for_label }}.value = parseInt(val1.value) + parseInt(val2.value)"></input>
				<label>Хол.вода ванная</label>
			</div>
			<div class="input-field col s12 m6">
				{{ form.cold_water }}
				<label for="{{ form.cold_water.id_for_label }}">Холодная вода (общая)</label>
			</div>


			<div class="input-field col s12 m3">
				<input name="val3" type="text" value=""></input>
				<label>Гор.вода кухня</label>
			</div>	
			<div class="input-field col s12 m3">	
				<input name="val4" type="text" value="" oninput="{{ form.hot_water.id_for_label }}.value = parseInt(val3.value) + parseInt(val4.value)"></input>
				<label>Гор.вода ванная</label>
			</div>
			<div class="input-field col s12 m6">
				{{ form.hot_water }}
				<label for="{{ form.hot_water.id_for_label }}">Горячая вода (общая)</label>
			</div>


			<div class="input-field col s12">
				{{ form.electricity }}
				<label for="{{ form.electricity.id_for_label }}">Электричество</label>
			</div>
			<div class="input-field col s12">
				{{ form.gaz }}
				<label for="{{ form.gaz.id_for_label }}">Газ</label>
			</div>
		</div>
		<div class="center-align">
		<button class="btn-floating btn-middle waves-effect waves-light" type="submit" name="action">
        	<i class="material-icons">add</i>
  		</button>
  	</div>
    </form>


</div>

{% endblock %}

service/templates/service/consumption.html
{% extends 'base.html' %}
{% block content%}

<div class="col s12 card-panel teal center-align">
<ul class="pagination">
 
    {% if consumption.has_previous %}
        <li>
        <a href="?page={{ consumption.previous_page_number }}" class="white-text">
        <i class="material-icons">chevron_left</i></a></li>
    {% endif %}
 
    {% for num in consumption.paginator.page_range %}
        {% if num == consumption.number %}
            <li>
            <span class="current"><b>{{ num }}</b></span></li>
        {% else %}
           <li>
           <a href="?page={{ num }}"> {{ num }}</a></li>
        {% endif %} 
    {% endfor %}
 
    {% if consumption.has_next %}
      <li>
      <a href="?page={{ consumption.next_page_number }}" class="white-text">
      <i class="material-icons">chevron_right</i></a></li>
    {% endif %}
 
</ul>
</div>
       

        <table>

        <tr>

            <td>Дата</td>
            <td>Хол.Вода</td>
            <td>Гор.Вода</td>
            <td>Эл-во</td>
            <td>Газ</td>

        </tr>

        {% for item in consumption %}

            <tr>

                <td>{{ item.pub_date }}</td>
                <td>{{ item.cold_water }}</td>
                <td>{{ item.hot_water }}</td>
                <td>{{ item.electricity }}</td>
                <td>{{ item.gaz }}</td>

            </tr>

        {% endfor %}

        </table>
       
        <div class="center-align">
        <a href="{% url 'service:upd' %}" class="btn-floating btn-middle waves-effect waves-light">
        <i class="material-icons">refresh</i></a>
    </div>
 
{% endblock %}

service/templates/service/index.html
{% extends 'base.html' %}



{% block content%}
<div class="col s12 card-panel teal center-align">
<ul class="pagination">
 
    {% if service.has_previous %}
        <li>
        <a href="?page={{ service.previous_page_number }}" class="white-text">
        <i class="material-icons">chevron_left</i></a></li>
    {% endif %}
 
    {% for num in service.paginator.page_range %}
        {% if num == service.number %}
            <li>
            <span class="current"><b>{{ num }}</b></span></li>
        {% else %}
           <li>
           <a href="?page={{ num }}"> {{ num }}</a></li>
        {% endif %} 
    {% endfor %}
 
    {% if service.has_next %}
      <li>
      <a href="?page={{ service.next_page_number }}" class="white-text">
      <i class="material-icons">chevron_right</i></a></li>
    {% endif %}
 
</ul>
</div>
        <table>

        <tr>

            <td>Дата</td>
            <td>Хол.Вода</td>
            <td>Гор.Вода</td>
            <td>Эл-во</td>
            <td>Газ</td>

        </tr>

        {% for service_item in service %}

            <tr>

                <td>{{ service_item.pub_date }}</td>
                <td>{{ service_item.cold_water }} </td>
                <td>{{ service_item.hot_water }}</td>
                <td>{{ service_item.electricity }}</td>
                <td>{{ service_item.gaz }}</td>

            </tr>

        {% endfor %}

        </table>

    

{% endblock %}