p1/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('service/', include('service.urls')),
    path('send_mail/', include('send_mail.urls')),
    path('send_sms/', include('send_sms.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

                 ]

service/urls.py
from django.urls import path
from . import views

app_name = 'service'
urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'add/', views.add, name='add'),
    path(r'consuming/', views.consuming, name='consuming'),
    path(r'upd/', views.consuming_upd, name='upd'),

]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.css' %}">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" sizes="32x32">
    

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<title>{% if title %}{{ title }} | {% endif %}Django sandbox project</title>
  </head>

  <body>
  <nav>
    <div class="nav-wrapper blue-grey darken-1">
      <a href="#!" class="brand-logo center">{{ title }}</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="left hide-on-med-and-down">
        <li>
          <a href="{% url 'service:add' %}" title="Добавить показания"><i class="material-icons">add_circle_outline</i></a></li>
        <li>
          <a href="{% url 'service:home' %}" title="Просмотреть показания"><i class="material-icons">visibility</i></a></li>
        <li>
          <a href="{%url 'service:consuming'%}" title="Просмотреть расход"><i class="material-icons">assessment</i></a></li>
        <li>
          <a href="/send_mail/" title="Отправить воду"><i class="material-icons">mail</i></a></li>
        <li>
          <a href="/send_sms/" title="Отправить электричество и газ"><i class="material-icons">sms</i></a></li>
      </ul>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        {% if user.is_authenticated %}
        <li>{{ user.username }}</li>
        <li><a href="{% url 'logout'%}">Выход</a></li>
        <li></li>
        {% else %}
        <li><a href="{% url 'login'%}?next={{request.path}}">Вход</a></li>
        {% endif %}
      </ul>
      <ul class="side-nav" id="mobile-demo">
        {% if user.is_authenticated %}
        <li>{{ user.username }}<a href="{% url 'logout'%}">Выход</a></li>
        {% else %}
        <li><a href="{% url 'login'%}?next={{request.path}}">Вход</a></li>
        {% endif %}
        <div class="divider"></div>
        <li><a href="{% url 'service:add' %}" title="Добавить показания">Добавить</a></li>
        <li><a href="{% url 'service:home' %}">Показания</a></li>
        <li><a href="{%url 'service:consuming'%}">Расход</a></li>
        <li><a href="/send_mail/">Отправить воду</a></li>
        <li><a href="/send_sms/">Отправить эл-во и газ</a></li>
      </ul>
    </div>
  </nav>
  <div class="container login-f">
    <div class="row">
  		<div class="col s12 m8 offset-m2">
     		<div class="card blue-grey darken-1 z-depth-5">
          <div class="card-content white-text">
            {% block content %}{% endblock %}
       	  </div> 
        </div>
   		</div> 
    </div>
  </div>
    
  <footer class="page-footer blue-grey darken-1">
   <div class="footer-copyright">
      <div class="container">
        © 2019 Nikita [Neex] Tkachenko
        <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </footer>
            
    <!--Import jQuery before materialize.js-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'js/materialize.js' %}"></script>
    <script type="text/javascript">
      $(".button-collapse").sideNav();
    </script>
    
  </body>
</html>