p1/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('service/', include('service.urls')),
    path('send_mail/', include('send_mail.urls')),
    path('send_sms/', include('send_sms.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

                 ]

send_mail/urls.py
from django.urls import path
from . import views

app_name = 'send_mail'
urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'send/', views.success, name='success'),
    

]

send_mail/models.py
from __future__ import unicode_literals
from django.db import models

class UserEmail(models.Model):
    email = models.CharField(max_length=200)

send_mail/forms.py
forms.py

send_mail/views.py
#coding: utf-8
from django.shortcuts import render
from django.core.mail import send_mail
from service.models import Services
from django.utils import timezone
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    service = Services.objects.order_by('-id')[:1]
    h_water = service[0].hot_water
    c_water = service[0].cold_water
    n = '\n'
    message = '{}{}{}{}{}{}{}'.format('Огородная 93/95, кв. 84', n, 'Горячая вода: ', str(h_water), n, 'Холодная вода: ', str(c_water))
    context = {
        'title': 'Отправить показания водяных счетчиков',
        'message' : message
                     }
    return render(request, 'send_mail/index.html', context)
@login_required
def success(request): 
    #today = timezone.now()
    month = timezone.now().strftime('%B')
    year = timezone.now().strftime('%Y')
    theme = 'Показания счетчиков за ' + month + ' ' + year
    email = request.POST.get('email', '')
    message = request.POST.get('message', '')
    send_mail(theme, str(message), 'neex@nm.ru', [email], fail_silently=False)
    return render(request, 'send_mail/success.html')

send_mail/templates/send_mail/index.html
{% extends 'base.html' %}
{% block content%}

<form class="col s12" method="POST" id="form_ID" action="{% url 'send_mail:success' %}">
	{% csrf_token %} 
	<div class="input-field col s12">
    <i class="material-icons prefix">email</i>
    <label for="email">Email</label>
    <input id="email" type="email" name="email" class="validate">
	</div>
	<div class="input-field col s12">
   <i class="material-icons prefix">mode_edit</i>
   <label for="message">Текст письма</label>
   <textarea  id="textarea1" name="message" class="materialize-textarea">{{ message }}</textarea>
  </div>
</form>
<div class="center-align">
  <a class="btn-floating btn-middle waves-effect waves-light" onclick="isEmail(document.getElementById('email').value)">
  <i class="material-icons">send</i></a>
</div>




<script type="text/javascript">
      function isEmail(email) {
        var re = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        if (re.test(email)) {
          document.getElementById('form_ID').submit();
        } else{
          alert("Введен не правильный адрес email");
        }
      }
    </script>

{% endblock %}

send_mail/templates/send_mail/success.html
{% extends 'base.html' %}
{% block content%}


  <i class="material-icons">report</i>
  <span class="white-text">Показания счетчиков воды отправлены
  <br>
  <br>
</span>


{% endblock %}